### PR TITLE
Update even more screenshots

### PR DESCRIPTION
**Pull request by nickc95**
#### Checklist

- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/docs/blob/master/CONTRIBUTING.md) before creating this PR.

##### Description of change
Fixed typo on admin console, update all related screenshots. Update user management screenshots due to description change.

### CODE REVIEW

**Comment by pareek-narendra** [comment]
- Edit button should be highlighted
docs/content/assets/howto/manage-email-password-login/edit-login.png

- Most of the images in 2fa having `communication settings` word in the SMS passcode description.

**Review by pareek-narendra — CHANGES_REQUESTED** [review]
Please check the comment

**Comment by nickc95** [comment]
Hi Narendra, as per https://loginradius.atlassian.net/browse/PAC-5916 , the presence of `communication settings` is deliberate, and for now should remain this way. Edited the edit-login.png.

**Review by nickc95 — COMMENTED** [review]
Edited edit-login.png

**Review by pareek-narendra — DISMISSED** [review]

**Review by nickc95 — COMMENTED** [review]
Updated 2fa screenshots.

**Review by pareek-narendra — APPROVED** [review]

**Pull request merged**
