### PR TITLE
Update Readme, files in guides, and How-Tos

### PR DESCRIPTION
**Pull request by dheeraj-2000**
#### Checklist

- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/docs/blob/master/CONTRIBUTING.md) before creating this PR.

##### Description of change
1. Added links to download/update prerequisites in almost all guide files (wherever required), along with some other minor changes in text.
2. Spelling fix in _work with SOTT_,  and added break line below the images in various _How Tos_ files
3. Updated README

### CODE REVIEW

**Comment by dheeraj-2000** [comment]
Hey @IArchna can you please review this PR.

**Comment by aman-agrwl** [comment]
@dheeraj-2000 

Please rebase your branch with master and then submit any PR

**Comment by dheeraj-2000** [comment]
Hello @aman-agrwl Sir, please review and merge this PR if it looks fine. I've rebased my branch.

**Comment by dheeraj-2000** [comment]
Hello @pareek-narendra & @puneetsingh24 Sir, please review and appprove this PR

**Pull request closed without merging**
