### PR TITLE
Fix: corrected few grammatical errors in the file

### PR DESCRIPTION
**Pull request by pushparavi123**
Corrected few grammatical errors in the file

##### Description of change

Removed few repeated words like application in a sentence and also corrected the grammatical error in few sentences.

### CODE REVIEW

**Comment by aman-agrwl** [comment]
@pushparavi123 

Thanks for contributing to the repo. We can surely improve as per your suggestions. But as per the HacktoberFest guideline, we will not be accepting minor text fixes as a PR. Please suggest and improve some quantifiable changes in the pull request to make your PR eligible for HacktoberFest.

**Review by pareek-narendra — COMMENTED** [review]
Not Approved! Please add some valuable changes to make the PR eligible for Hacktoberfest.

**Comment by pushparavi123** [comment]
What changes should I have to add more on the documentation so that PR can be merged. I have already corrected all the typo errors in the file. If you can let me know what all changes should I make for the PR to merged. It would be nice.

**Comment by pareek-narendra** [comment]
@pushparavi123 you can improve a few more docs in the same PR to make this PR eligible.

**Pull request closed without merging**
